In [45]:
# Fundamentals of Quantum Computation 
# Basic Arithmetic Operations & Complex No.  

In [46]:
# Complex No. Format 
1j*1j

(-1+0j)

In [47]:
y = 4+8j

In [48]:
x = 5-5j

In [49]:
# 4 and 5 are real, 8 and 5 are imaginary 

In [50]:
import numpy as np 

In [51]:
print("Real of z: ", np.real( x ))

Real of z:  5.0


In [52]:
print("Image of w: ", np.imag( x ))

Image of w:  -5.0


In [53]:
y+x

(9+3j)

In [54]:
# Complex Conjugates 

In [55]:
x

(5-5j)

In [56]:
np.conj( x )

(5+5j)

In [57]:
# Norms / Abs Values 

In [58]:
# ||x|| = ( sqrt ){ xx* } = ( sqrt ){ |x^2| }

In [59]:
np.abs( x )

7.0710678118654755

In [60]:
# Row Vectors / Col Vectors / Bra-Ket Notation 

In [61]:
vectorRow = np.array( [ 1, 2+2j, 3] )

In [62]:
vectorRow

array([1.+0.j, 2.+2.j, 3.+0.j])

In [63]:
vectorCol = np.array( [ [ 1 ],[ 2+2j ],[ 3j ] ] )

In [64]:
vectorCol

array([[1.+0.j],
       [2.+2.j],
       [0.+3.j]])

In [65]:
# Row vectors in Quantum Mechanics are called bra-vectors
# Notation : 
# <A| = ( a1, a2, ..., an )

In [66]:
# Column vectors are called ket-vectors
# Notation : 
# |B> =
# [ b1  |
# | b2  |
# | ... |
# | bn  ]

In [67]:
# Inner Product ( Row vs Column )
# Sum( a1b1 + a2b2 + ... + anbn )  

In [68]:
# Excercise : Define A as a 4*1 Matrix 
A = np.array([[ 1 ], [  4-5j ], [ 5 ], [ -3 ] ])

In [69]:
# Define a B as a 1*4 Matrix 
B = np.array([ 1j, -2, 3, -4j ])

In [70]:
# Compute <B|A> ( Inner Product )
np.dot( B,A )

array([7.+23.j])

In [71]:
# Matrices
Matrix = np.matrix([ [ 2-1j, -3 ],[ -5j, 2 ] ])
print( Matrix )

[[ 2.-1.j -3.+0.j]
 [-0.-5.j  2.+0.j]]


In [72]:
# Hemitian conjugates = The conjugate transpose of the matrix
Matrix.H

matrix([[ 2.+1.j, -0.+5.j],
        [-3.-0.j,  2.-0.j]])

In [73]:
# Tensor Products of Matrices
# Multiply every value in the first matrix by the entire second matrix 
# Create new Matrix of equal proportions 
matrixTwo = np.matrix([ [ 2, -3-1j ],[ -6j, 3 ] ])
np.kron( Matrix, matrixTwo )

matrix([[  4. -2.j,  -7. +1.j,  -6. +0.j,   9. +3.j],
        [ -6.-12.j,   6. -3.j,   0.+18.j,  -9. +0.j],
        [  0.-10.j,  -5.+15.j,   4. +0.j,  -6. -2.j],
        [-30. +0.j,   0.-15.j,   0.-12.j,   6. +0.j]])